services:
  - type: web
    name: urlshortener-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    rootDir: .
    healthCheckPath: /api/health
